version: '3.7'

networks:
  main:

services:

  app:
    image: app-image
    build:
      context: .
#    container_name: app
    hostname: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - main
    restart: on-failure

#  db:
#    image: 'postgres:13.1-alpine'
##    container_name: db
#    hostname: db
#    environment:
#      - POSTGRES_USER=compose-postgres
#      - POSTGRES_PASSWORD=compose-postgres
#    networks:
#      - main
#    restart: on-failure
#
#volumes:
#  postgresql-data:
